export const RAW_RESORTS = [
  { name: "Vail", lat: 39.6403, lon: -106.3742, pass: "epic" },
  { name: "Beaver Creek", lat: 39.6042, lon: -106.5165, pass: "epic" },
  { name: "Breckenridge", lat: 39.4817, lon: -106.0384, pass: "epic" },
  { name: "Keystone", lat: 39.6069, lon: -105.9718, pass: "epic" },
  { name: "Crested Butte", lat: 38.8991, lon: -106.9653, pass: "epic" },
  { name: "Park City", lat: 40.6514, lon: -111.5080, pass: "epic" },
  { name: "Kirkwood", lat: 38.6850, lon: -120.0653, pass: "epic" },
  { name: "Heavenly", lat: 38.9353, lon: -119.9400, pass: "epic" },
  { name: "Northstar", lat: 39.2746, lon: -120.1210, pass: "epic" },
  { name: "Stowe", lat: 44.5303, lon: -72.7814, pass: "epic" },
  { name: "Okemo", lat: 43.4017, lon: -72.7170, pass: "epic" },
  { name: "Mount Sunapee", lat: 43.3264, lon: -72.0819, pass: "epic" },
  { name: "Stevens Pass", lat: 47.7453, lon: -121.0890, pass: "epic" },
  { name: "Whistler Blackcomb", lat: 50.1163, lon: -122.9574, pass: "epic" },
  { name: "Afton Alps", lat: 44.8569, lon: -92.9036, pass: "epic" },
  { name: "Mt. Brighton", lat: 42.5392, lon: -83.8136, pass: "epic" },
  { name: "Wilmot Mountain", lat: 42.4978, lon: -88.1868, pass: "epic" },
  { name: "Attitash", lat: 44.0833, lon: -71.2292, pass: "epic" },
  { name: "Wildcat Mountain", lat: 44.2636, lon: -71.2389, pass: "epic" },
  { name: "Crotched Mountain", lat: 43.0164, lon: -71.8764, pass: "epic" },
  { name: "Hunter Mountain", lat: 42.2028, lon: -74.2258, pass: "epic" },
  { name: "Mount Snow", lat: 42.9603, lon: -72.9206, pass: "epic" },
  { name: "Jack Frost / Big Boulder", lat: 41.0594, lon: -75.6163, pass: "epic" },
  { name: "Roundtop Mountain", lat: 40.1086, lon: -76.9272, pass: "epic" },
  { name: "Liberty Mountain", lat: 39.7553, lon: -77.3753, pass: "epic" },
  { name: "Whitetail Resort", lat: 39.7428, lon: -77.9342, pass: "epic" },
  { name: "Seven Springs", lat: 40.0231, lon: -79.2978, pass: "epic" },
  { name: "Hidden Valley", lat: 40.0500, lon: -79.2544, pass: "epic" },
  { name: "Laurel Mountain", lat: 40.1614, lon: -79.1658, pass: "epic" },
  { name: "Perisher", lat: -36.4069, lon: 148.4094, pass: "epic" },
  { name: "Falls Creek", lat: -36.8625, lon: 147.2753, pass: "epic" },
  { name: "Hotham", lat: -36.9781, lon: 147.1706, pass: "epic" },
  { name: "Hakuba Valley", lat: 36.6983, lon: 137.8319, pass: "epic" },
  { name: "Rusutsu", lat: 42.7500, lon: 140.5667, pass: "epic" },
  { name: "Andermatt-Sedrun", lat: 46.6342, lon: 8.5942, pass: "epic" },
  { name: "Verbier (4 Vallées)", lat: 46.0969, lon: 7.2286, pass: "epic" },
  { name: "Crans-Montana", lat: 46.3167, lon: 7.4833, pass: "epic" },
  { name: "Les 3 Vallées", lat: 45.3833, lon: 6.5833, pass: "epic" },
  { name: "Paradiski", lat: 45.5667, lon: 6.8500, pass: "epic" },
  { name: "Tignes", lat: 45.4681, lon: 6.9064, pass: "epic" },
  { name: "Val d'Isère", lat: 45.4481, lon: 6.9806, pass: "epic" },
  { name: "Telluride", lat: 37.9375, lon: -107.8123, pass: "epic" },
  { name: "Aspen Snowmass", lat: 39.2084, lon: -106.9490, pass: "ikon" },
  { name: "Steamboat", lat: 40.4572, lon: -106.8045, pass: "ikon" },
  { name: "Winter Park", lat: 39.8841, lon: -105.7625, pass: "ikon" },
  { name: "Copper Mountain", lat: 39.5022, lon: -106.1497, pass: "ikon" },
  { name: "Eldora", lat: 39.9375, lon: -105.5828, pass: "ikon" },
  { name: "Arapahoe Basin", lat: 39.6425, lon: -105.8719, pass: "ikon" },
  { name: "Big Sky", lat: 45.2836, lon: -111.4008, pass: "ikon" },
  { name: "Jackson Hole", lat: 43.5877, lon: -110.8279, pass: "ikon" },
  { name: "Alta", lat: 40.5884, lon: -111.6386, pass: "ikon" },
  { name: "Snowbird", lat: 40.5830, lon: -111.6508, pass: "ikon" },
  { name: "Deer Valley", lat: 40.6375, lon: -111.4783, pass: "ikon" },
  { name: "Brighton Resort", lat: 40.5980, lon: -111.5833, pass: "ikon" },
  { name: "Solitude", lat: 40.6197, lon: -111.5922, pass: "ikon" },
  { name: "Mammoth Mountain", lat: 37.6308, lon: -119.0326, pass: "ikon" },
  { name: "June Mountain", lat: 37.7675, lon: -119.0906, pass: "ikon" },
  { name: "Big Bear Mountain", lat: 34.2364, lon: -116.8906, pass: "ikon" },
  { name: "Squaw Valley Alpine Meadows", lat: 39.1968, lon: -120.2354, pass: "ikon" },
  { name: "Killington", lat: 43.6045, lon: -72.8201, pass: "ikon" },
  { name: "Sugarbush", lat: 44.1358, lon: -72.9003, pass: "ikon" },
  { name: "Stratton", lat: 43.1133, lon: -72.9081, pass: "ikon" },
  { name: "Tremblant", lat: 46.2094, lon: -74.5858, pass: "ikon" },
  { name: "Blue Mountain (Ontario)", lat: 44.5008, lon: -80.3164, pass: "ikon" },
  { name: "SkiBig3 (Banff)", lat: 51.1631, lon: -115.5631, pass: "ikon" },
  { name: "Revelstoke", lat: 51.0267, lon: -118.1631, pass: "ikon" },
  { name: "Cypress Mountain", lat: 49.3964, lon: -123.2047, pass: "ikon" },
  { name: "Red Mountain", lat: 49.1042, lon: -117.8453, pass: "ikon" },
  { name: "Sun Peaks", lat: 50.8833, lon: -119.8833, pass: "ikon" },
  { name: "Crystal Mountain", lat: 46.9283, lon: -121.5047, pass: "ikon" },
  { name: "The Summit at Snoqualmie", lat: 47.4206, lon: -121.4139, pass: "ikon" },
  { name: "Loon Mountain", lat: 44.0364, lon: -71.6214, pass: "ikon" },
  { name: "Sugarloaf", lat: 45.0314, lon: -70.3131, pass: "ikon" },
  { name: "Sunday River", lat: 44.4728, lon: -70.8572, pass: "ikon" },
  { name: "Boyne Highlands", lat: 45.4675, lon: -84.9264, pass: "ikon" },
  { name: "Boyne Mountain", lat: 45.1653, lon: -84.9319, pass: "ikon" },
  { name: "Taos", lat: 36.5964, lon: -105.4542, pass: "ikon" },
  { name: "Snowshoe", lat: 38.4106, lon: -79.9942, pass: "ikon" },
  { name: "Windham Mountain", lat: 42.2978, lon: -74.2578, pass: "ikon" },
  { name: "Chamonix (Mont Blanc)", lat: 45.9237, lon: 6.8694, pass: "ikon" },
  { name: "Zermatt", lat: 46.0207, lon: 7.7491, pass: "ikon" },
  { name: "St. Moritz (Diavolezza)", lat: 46.4131, lon: 9.9975, pass: "ikon" },
  { name: "Kitzbühel", lat: 47.4492, lon: 12.3919, pass: "ikon" },
  { name: "Lech Zürs am Arlberg", lat: 47.2083, lon: 10.1419, pass: "ikon" },
  { name: "Dolomiti Superski", lat: 46.5367, lon: 11.8439, pass: "ikon" },
  { name: "Thredbo", lat: -36.5053, lon: 148.3072, pass: "ikon" },
  { name: "Niseko United", lat: 42.8625, lon: 140.6875, pass: "ikon" },
  { name: "Lotte Arai", lat: 36.9481, lon: 138.2000, pass: "ikon" },
  { name: "Valle Nevado", lat: -33.3583, lon: -70.2678, pass: "ikon" },
  { name: "Palisades Tahoe", lat: 39.1968, lon: -120.2354, pass: "ikon" },
  { name: "Panorama", lat: 50.4600, lon: -116.2350, pass: "ikon" },
  { name: "Schweitzer", lat: 48.3675, lon: -116.6225, pass: "ikon" },
  { name: "Sun Valley", lat: 43.6975, lon: -114.3514, pass: "ikon" },
  { name: "Snowbasin", lat: 41.2161, lon: -111.8569, pass: "ikon" }
];

export const DEFAULT_WEBCAM_PAGES = {
  "vail": "https://www.vail.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "beaver creek": "https://www.beavercreek.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "breckenridge": "https://www.breckenridge.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "keystone": "https://www.keystoneresort.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "crested butte": "https://www.skicb.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "park city": "https://www.parkcitymountain.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "heavenly": "https://www.skiheavenly.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "northstar": "https://www.northstarcalifornia.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "kirkwood": "https://www.kirkwood.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "stevens pass": "https://www.stevenspass.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "stowe": "https://www.stowe.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "okemo": "https://www.okemo.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "mount snow": "https://www.mountsnow.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "mount sunapee": "https://www.mountsunapee.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "attitash": "https://www.attitash.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "wildcat mountain": "https://www.skiwildcat.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "hunter mountain": "https://www.huntermtn.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "seven springs": "https://www.7springs.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "roundtop mountain": "https://www.skiroundtop.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "liberty mountain": "https://www.libertymountainresort.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "whitetail resort": "https://www.skiwhitetail.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "hidden valley": "https://www.hiddenvalleyresort.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "laurel mountain": "https://www.laurelmountainski.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "afton alps": "https://www.aftonalps.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "mt. brighton": "https://www.mtbrighton.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "wilmot mountain": "https://www.wilmotmountain.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "whistler blackcomb": "https://www.whistlerblackcomb.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  "aspen snowmass": "https://www.aspensnowmass.com/four-mountains/mountain-cams",
  "big sky": "https://www.bigskyresort.com/current-conditions/webcams",
  "crystal mountain": "https://crystalmt.com/mountain/report-webcams/",
  "deer valley": "https://www.deervalley.com/explore-the-mountain/webcams",
  "jackson hole": "https://www.jacksonhole.com/live-mountain-cams",
  "killington": "https://www.killington.com/the-mountain/conditions-weather/webcam/",
  "mammoth mountain": "https://www.mammothmountain.com/on-the-mountain/mammoth-webcam",
  "palisades tahoe": "https://www.palisadestahoe.com/mountain-information/webcams",
  "snowbird": "https://www.snowbird.com/the-mountain/webcams/view-all-webcams/",
  "solitude": "https://www.solitudemountain.com/mountain-and-village/webcams",
  "steamboat": "https://www.steamboat.com/the-mountain/live-cams",
  "stratton": "https://www.stratton.com/the-mountain/mountain-conditions/webcams",
  "sugarbush": "https://www.sugarbush.com/mountain/webcams",
  "tremblant": "https://www.tremblant.ca/mountain-village/webcam",
  "winter park": "https://www.winterparkresort.com/the-mountain/mountain-cams",
  "copper mountain": "https://www.coppercolorado.com/the-mountain/webcams/",
  "eldora": "https://www.eldora.com/the-mountain/webcams/snow-stake-cam/",
  "june mountain": "https://www.junemountain.com/mountain-information/live-cams",
  "snowshoe": "https://www.snowshoemtn.com/media-room/web-cams",
  "alta": "https://www.alta.com/weather",
  "arapahoe basin": "https://www.arapahoebasin.com/mountain-cams/",
  "cypress mountain": "https://www.cypressmountain.com/webcams",
  "red mountain": "https://www.redresort.com/report?cams",
  "revelstoke": "https://www.revelstokemountainresort.com/mountain/conditions/webcams/",
  "snowbasin": "https://www.snowbasin.com/the-mountain/web-cams",
  "sugarloaf": "https://www.sugarloaf.com/mountain-report",
  "sunday river": "https://www.sundayriver.com/mountain-report",
  "sun valley": "https://www.sunvalley.com/the-mountain/web-cams",
  "taos": "https://www.skitaos.com/lifts?section=weather-forecast",
  "the summit at snoqualmie": "https://www.summitatsnoqualmie.com/webcams",
  "loon mountain": "https://www.loonmtn.com/mountain-report",
  "big bear mountain": "https://www.bigbearmountainresort.com/webcams",
  "blue mountain": "https://www.bluemountain.ca/mountain/webcams"
};

export const PASS_FILTERS = [
  { id: "all", label: "All Resorts" },
  { id: "favorites", label: "Favorites" },
  { id: "epic", label: "Epic Pass" },
  { id: "ikon", label: "Ikon Pass" }
];

export const REGION_FILTERS = [
  { id: "all", label: "Global" },
  { id: "north-america", label: "North America" },
  { id: "alps", label: "Alps" },
  { id: "japan", label: "Japan" },
  { id: "south", label: "Southern" }
];

export const DEG2RAD = Math.PI / 180;
export const CESIUM_ION_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4NWNlODYwNi1jZjI3LTRlNzctOGY1OC1jMjk0NDA0NjdmMmQiLCJpZCI6NDAxMDI1LCJpYXQiOjE3NzMwOTk0NDl9.A9BgNlPXdl8qNHVWJ4pZebRmRb7f5ll1hw01a1Q2N4E';
export const BILLBOARD_HEIGHT = 220;
export const HOVER_MARKER_HEIGHT = 340;
export const SELECTED_MARKER_HEIGHT = 520;
export const FAVORITES_KEY = "snow-scout-favorites";

export const DEFAULT_CONDITION_PAGES = {
  "copper mountain": "https://www.coppercolorado.com/the-mountain/conditions-weather/snow-report/",
  "snowbird": "https://www.snowbird.com/the-mountain/mountain-report/current-conditions-weather/",
  "solitude": "https://www.solitudemountain.com/mountain-and-village/conditions-and-maps"
};

export const RESORT_SOURCE_ALIASES = new Map([
  ['big bear', 'big bear mountain'],
  ['big bear mountain', 'big bear mountain'],
  ['big bear mountain resort', 'big bear mountain'],
  ['blue mountain', 'blue'],
  ['brighton resort', 'brighton'],
  ['copper', 'copper mountain'],
  ['crystal mountain', 'crystal'],
  ['cypress mountain', 'cypress'],
  ['hunter mountain', 'hunter'],
  ['jack frost big boulder', 'jack frost'],
  ['june', 'june mountain'],
  ['liberty mountain', 'liberty'],
  ['loon mountain', 'loon'],
  ['mammoth mountain', 'mammoth'],
  ['mt brighton', 'mt brighton'],
  ['mt brighton mountain', 'mt brighton'],
  ['palisades tahoe', 'palisades tahoe'],
  ['pico mountain', 'pico'],
  ['red mountain', 'red'],
  ['roundtop mountain', 'roundtop'],
  ['squaw valley alpine meadows', 'palisades tahoe'],
  ['summit at snoqualmie', 'summit at snoqualmie'],
  ['sunday river resort', 'sunday river'],
  ['the summit at snoqualmie', 'summit at snoqualmie'],
  ['whitetail resort', 'whitetail'],
  ['wildcat mountain', 'wildcat']
]);